server:
  port: ${SERVER_PORT:-8082}
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:-ms-accounts}
  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    username: ${POSTGRES_USER:-postgres}
    password: ${POSTGRES_PASSWORD:-Passw0rd.}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: ${RABBITMQ_PORT:-5672}
    username: ${RABBITMQ_USER:-admin}
    password: ${RABBITMQ_PASSWORD:-admin}
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/