server:
  port: 8082
spring:
  application:
    name: ms-accounts
  datasource:
    url: jdbc:postgresql://postgres:5432/sofka
    username: postgres
    password: Passw0rd.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://ms-eureka:8761/eureka/